const PREFIX = 'HOMEPAGE';
export const GET_POPULAR_TAGS = `${PREFIX}_GET_POPULAR_TAGS`;
export const GET_TAGS_BY_KEYWORD = `${PREFIX}_GET_TAGS_BY_KEYWORD`;
export const GET_FANPAGES_BY_KEYWORD = `${PREFIX}_GET_FANPAGES_BY_KEYWORD`;
export const GET_SPECIAL_FANPAGES = `${PREFIX}_GET_SPECIAL_FANPAGES`;
export const GET_SPECIAL_CONTENTS = `${PREFIX}_GET_SPECIAL_CONTENTS`;
export const SET_SELECTED_CATEGORY_IDS = `${PREFIX}_SET_SELECTED_CATEGORY_IDS`;
