export const GET_CREATED_CONTENTS = 'GET_CREATED_CONTENTS';
export const GET_FEEDBACK_KEYWORDS = 'GET_FEEDBACK_KEYWORDS';
export const GET_GOOGLE_SUBJECTS = 'GET_GOOGLE_SUBJECTS';
export const GET_FEEDBACK_SUGGESTIONS = 'GET_FEEDBACK_SUGGESTIONS';
export const GET_TREND_SUGGESTIONS = 'GET_TREND_SUGGESTIONS';
export const GET_CONTENT_SUGGESTIONS = 'GET_CONTENT_SUGGESTIONS';

export const GET_100_DON_CHARTS = 'GET_100_DON_CHARTS';
export const GET_100_DON_DETAILS = 'GET_100_DON_DETAILS';

export const CHANGE_STATE_CREATE_CONTENT_FORM =
  'CHANGE_STATE_CREATE_CONTENT_FORM';
export const CHANGE_STATE_GET_MEDIA_FORM = 'CHANGE_STATE_GET_MEDIA_FORM';

export const SET_IMAGES_CONTENT = 'SET_IMAGES_CONTENT';
export const SET_VIDEO_CONTENT = 'SET_VIDEO_CONTENT';

export const REMOVE_VIDEO_CONTENT = 'REMOVE_VIDEO_CONTENT';

export const CHANGE_STATE_GET_IMAGES = 'CHANGE_STATE_GET_IMAGES';
export const CHANGE_STATE_GET_VIDEO = 'CHANGE_STATE_GET_VIDEO';
export const CHANGE_STATE_GET_EMOJI = 'CHANGE_STATE_GET_EMOJI';

export const GET_ALL_CATEGORIES = 'GET_ALL_CATEGORIES';

// define state for formular form
export const CHANGE_STATE_SHOW_FORMULAR_POPUP =
  'CHANGE_STATE_SHOW_FORMULAR_POPUP';
export const CHANGE_STATE_SHOW_FORMULAR_POPUP_FORM =
  'CHANGE_STATE_SHOW_FORMULAR_POPUP_FORM';

export const CHANGE_STATE_SELECTED_KEYWORD = 'CHANGE_STATE_SELECTED_KEYWORD';

// Use For Popup Content
export const CHANGE_STATE_SHOW_POPUP_CONTENT =
  'CHANGE_STATE_SHOW_POPUP_CONTENT';
export const CHANGE_STATE_CATEGORIES_POPUP = 'CHANGE_STATE_CATEGORIES_POPUP';
export const CHANGE_STATE_SELECTED_CAT = 'CHANGE_STATE_SELECTED_CAT';

// feedbacks form
export const CHANGE_STATE_FEEDBACKS_FORM = 'CHANGE_STATE_FEEDBACKS_FORM';
export const CHANGE_STATE_FEEDBACKS_TYPE = 'CHANGE_STATE_FEEDBACKS_TYPE';
export const CHANGE_FEEDBACK_SETTINGS = 'CHANGE_FEEDBACK_SETTINGS';
export const PUSH_FEEDBACK_MESSAGE = 'PUSH_FEEDBACK_MESSAGE';
export const REMOVE_FEEDBACK_MESSAGE = 'REMOVE_FEEDBACK_MESSAGE';
export const UPDATE_FEEDBACK_MESSAGE = 'UPDATE_FEEDBACK_MESSAGE';
export const RESET_FEEDBACK_DATA = 'RESET_FEEDBACK_DATA';
export const SAVE_FEEDBACK_DATA = 'SAVE_FEEDBACK_DATA';
export const SET_CURRENT_FEEDBACK = 'SET_CURRENT_FEEDBACK';

// Use for Contents
export const GET_CATEGORIES_INFO_BY_SLUG = 'GET_CATEGORIES_INFO_BY_SLUG';
export const GET_CONTENTS = 'GET_CONTENTS';
export const GET_SPECIAL_CONTENTS = 'GET_SPECIAL_CONTENTS';
export const CREATE_CONTENT_GET_SPECIAL_CONTENTS =
  'CREATE_CONTENT_GET_SPECIAL_CONTENTS';
  export const CREATE_CONTENT_CHANGE_SELECTED_SPECIAL_CONTENT =
  'CREATE_CONTENT_CHANGE_SELECTED_SPECIAL_CONTENT';
export const GET_TOP_LIKE_CONTENTS = 'GET_TOP_LIKE_CONTENTS';
export const GET_TOP_SHARE_CONTENTS = 'GET_TOP_SHARE_CONTENTS';
export const GET_TOP_COMMENT_CONTENTS = 'GET_TOP_COMMENT_CONTENTS';
export const GET_TOTAL_CONTENTS = 'GET_TOTAL_CONTENTS';
export const GET_TOTAL_FANPAGES = 'GET_TOTAL_FANPAGES';
export const SET_CONTENT_DETAIL_TO_SHOW = 'SET_CONTENT_DETAIL_TO_SHOW';
export const SET_CONTENT_COMPARE = 'SET_CONTENT_COMPARE';
export const SET_LOADING = 'SET_LOADING';
export const CREATED_USER_CONTENT = 'CREATED_USER_CONTENT';
export const SET_CONTENT_TYPE = 'SET_CONTENT_TYPE';
export const GET_UNIQUE_FANPAGE = 'GET_UNIQUE_FANPAGE';

// Use for Search and Filter Content
export const SET_VALUE_FBID_TO_SEARCH = 'SET_VALUE_FBID_TO_SEARCH';
export const SET_VALUE_TYPE_OF_CONTENT_TO_SEARCH =
  'SET_VALUE_TYPE_OF_CONTENT_TO_SEARCH';
export const SET_VALUE_FROM_DATE_TO_SEARCH = 'SET_VALUE_FROM_DATE_TO_SEARCH';
export const SET_VALUE_TO_DATE_TO_SEARCH = 'SET_VALUE_TO_DATE_TO_SEARCH';
export const SET_VALUE_KEYWORDS_TO_SEARCH = 'SET_VALUE_KEYWORDS_TO_SEARCH';
export const SET_VALUE_OPTIONS_TO_SEARCH = 'SET_VALUE_OPTIONS_TO_SEARCH';
export const SET_VALUE_NUMS_LIKE_TO_FILTER = 'SET_VALUE_NUMS_LIKE_TO_FILTER';
export const SET_VALUE_NUMS_COMMENT_TO_FILTER =
  'SET_VALUE_NUMS_COMMENT_TO_FILTER';
export const SET_VALUE_NUMS_SHARE_TO_FILTER = 'SET_VALUE_NUMS_SHARE_TO_FILTER';
export const SET_VALUE_NUMS_WORD_TO_FILTER = 'SET_VALUE_NUMS_WORD_TO_FILTER';
export const SET_VALUE_FREQ_LIKE_TO_FILTER = 'SET_VALUE_FREQ_LIKE_TO_FILTER';
export const SET_VALUE_FREQ_COMMENT_TO_FILTER =
  'SET_VALUE_FREQ_COMMENT_TO_FILTER';
export const SET_VALUE_FREQ_SHARE_TO_FILTER = 'SET_VALUE_FREQ_SHARE_TO_FILTER';
export const SET_VALUE_FREQ_SAVE_TO_FILTER = 'SET_VALUE_FREQ_SAVE_TO_FILTER';
export const SET_VALUE_FREQ_TIME_TO_FILTER = 'SET_VALUE_FREQ_TIME_TO_FILTER';

//Use for Trending ContentsFilter
export const GET_TRENDING_WITH_KEYWORDS = 'GET_TRENDING_WITH_KEYWORDS';
// note : _ is private variable not change data
export const GET__TRENDING_WITH_KEYWORDS = 'GET__TRENDING_WITH_KEYWORDS';
export const GET_TOTAL_TRENDING_CONTENTS = 'GET_TOTAL_TRENDING_CONTENTS';
export const SET_KEYWORDS_SEARCH_TRENDINGS = 'GET_KEYWORDS_SEARCH_TRENDINGS';

export const GET_FACEBOOK_PRESETS = 'GET_FACEBOOK_PRESETS';
export const GET_FACEBOOK_PRESETS_SUCCESS = 'GET_FACEBOOK_PRESETS_SUCCESS';
export const SET_SELECTED_FACEBOOK_PRESET = 'SET_SELECTED_FACEBOOK_PRESET';
export const SET_IS_ACTIVE_PRESET = 'SET_IS_ACTIVE_PRESET';
