//Use for SuggestionsPopup
export const SET_SHOW_SUGGESTIONS_POPUP = 'SET_SHOW_SUGGESTIONS_POPUP';
export const SET_SHOW_SCHEDULE_ITEM_POPUP = 'SET_SHOW_SCHEDULE_ITEM_POPUP';
export const SET_SCHEDULE_ITEM_POPUP_TO_SHOW =
  'SET_SCHEDULE_ITEM_POPUP_TO_SHOW';
export const SET_SCHEDULE_ITEM_POPUP_TO_SHOW_MULTIPLE =
  'SET_SCHEDULE_ITEM_POPUP_TO_SHOW_MULTIPLE';
export const SET_SHOW_SCHEDULES_PANE = 'SET_SHOW_SCHEDULES_PANE';
export const SET_SHOW_REPORT_PANE = 'SET_SHOW_REPORT_PANE';
export const SET_SHOW_CREATE_SCHEDULE_POPUP = 'SET_SHOW_CREATE_SCHEDULE_POPUP';
export const SET_SHOW_SELECT_SUGGESTS_POPUP = 'SET_SHOW_SELECT_SUGGESTS_POPUP';
export const SET_VALUE_MONDAY = 'SET_VALUE_MONDAY';
export const SET_VALUE_SUNDAY = 'SET_VALUE_SUNDAY';
export const SET_VALUE_MONTH = 'SET_VALUE_MONTH';
export const SET_VALUE_YEAR = 'SET_VALUE_YEAR';
export const SET_IS_CHANGE_WEEK = 'SET_IS_CHANGE_WEEK';
export const SET_IS_CHANGE_MONTH = 'SET_IS_CHANGE_MONTH';
export const SET_VALUE_FIRST_DAY_OF_MONTH = 'SET_VALUE_FIRST_DAY_OF_MONTH';
export const SET_VALUE_WEEK = 'SET_VALUE_WEEK';
export const SET_SUGGESTION_CONTENT = 'SET_SUGGESTION_CONTENT';
export const SET_SUGGESTIONS_CONTENT = 'SET_SUGGESTIONS_CONTENT';
export const SET_VALUE_SORT_BY = 'SET_VALUE_SORT_BY';

export const GET_ALL_SCHEDULE_EVENTS = 'GET_ALL_SCHEDULE_EVENTS';
export const GET_USER_CREATED_CONTENTS = 'GET_USER_CREATED_CONTENTS';
export const GET_USER_CREATED_CONTENTS_SUCCESS = 'GET_USER_CREATED_CONTENTS_SUCCESS';
export const GET_USER_PLANS = 'GET_USER_PLANS';

export const GET_SUGGESTIONS_CONTENT = 'GET_SUGGESTIONS_CONTENT';
export const SET_IS_LOADING_GET_SUGGESTIONS_CONTENT =
  'SET_IS_LOADING_GET_SUGGESTIONS_CONTENT';
export const SET_CURRENT_SUGGESTIONS_SUBJECT =
  'SET_CURRENT_SUGGESTIONS_SUBJECT';

export const GET_SCHEDULE_CONTENTS = 'GET_SCHEDULE_CONTENTS';
export const GET_CONTENTS_BY_SCHEDULE = 'GET_CONTENTS_BY_SCHEDULE';
export const CHANGE_STATE_SCHEDULE_SHOW_CATEGORIES =
  'CHANGE_STATE_SCHEDULE_SHOW_CATEGORIES';
export const CHANGE_SCHEDULE_SELECTED_CATEGORY =
  'CHANGE_SCHEDULE_SELECTED_CATEGORY';

export const CHANGE_STATE_SCHEDULE_SHOW_SOURCE_IDEAS =
  'CHANGE_STATE_SCHEDULE_SHOW_SOURCE_IDEAS';

export const CHANGE_STATE_SCHEDULE_SHOW_SOURCE_IDEAS_AUTO =
  'CHANGE_STATE_SCHEDULE_SHOW_SOURCE_IDEAS_AUTO';

export const CHANGE_STATE_SHOW_SCHEDULE_COMMENTS_POPUP =
  'CHANGE_STATE_SHOW_SCHEDULE_COMMENTS_POPUP';

export const UPDATE_CURRENT_DATE_TIME = 'UPDATE_CURRENT_DATE_TIME';
export const GET_EVENT_CONTENTS = 'GET_EVENT_CONTENTS';

export const SET_SELECTED_CONTENT_TO_SCHEDULE =
  'SET_SELECTED_CONTENT_TO_SCHEDULE';

export const SET_IS_SHOW_FINAL_STEP = 'SET_IS_SHOW_FINAL_STEP';
export const SET_IS_SHOW_FINAL_STEP_AUTO = 'SET_IS_SHOW_FINAL_STEP_AUTO';

export const GET_FACEBOOK_DESTINATIONS = 'GET_FACEBOOK_DESTINATIONS';
export const GET_FACEBOOK_DESTINATIONS_SUCCESS =
  'GET_FACEBOOK_DESTINATIONS_SUCCESS';
export const GET_FACEBOOK_DESTINATIONS_FAILED =
  'GET_FACEBOOK_DESTINATIONS_FAILED';

export const GET_SCHEDULES = 'GET_SCHEDULES';
export const GET_SCHEDULES_SUCCESS = 'GET_SCHEDULES_SUCCESS';
export const GET_SCHEDULES_FAILED = 'GET_SCHEDULES_FAILED';

export const SET_SCHEDULE_WAITING_LIST = 'SET_SCHEDULE_WAITING_LIST';
export const SET_SCHEDULE_COMMENTS_WAITING_LIST =
  'SET_SCHEDULE_COMMENTS_WAITING_LIST';

export const SET_CURRENT_SCHEDULE_CONTENT = 'SET_CURRENT_SCHEDULE_CONTENT';

export const SET_CURRENT_SCHEDULE_CONTENT_TYPE =
  'SET_CURRENT_SCHEDULE_CONTENT_TYPE';
export const SET_CURRENT_SCHEDULE = 'SET_CURRENT_SCHEDULE';

export const CHANGE_STATE_SHOW_MANAGE_SCHEDULE =
  'CHANGE_STATE_SHOW_MANAGE_SCHEDULE';

export const MANAGE_SET_CURRENT_SCHEDULE = 'MANAGE_SET_CURRENT_SCHEDULE';
export const MANAGE_GET_SCHEDULE_CONTENTS = 'MANAGE_GET_SCHEDULE_CONTENTS';
export const MANAGE_GET_SCHEDULE_CONTENTS_SUCCESS =
  'MANAGE_GET_SCHEDULE_CONTENTS_SUCCESS';

export const COMMENT_SET_CURRENT_SCHEDULE = 'COMMENT_SET_CURRENT_SCHEDULE';
export const COMMENT_GET_SCHEDULE_CONTENTS = 'COMMENT_GET_SCHEDULE_CONTENTS';
export const COMMENT_GET_SCHEDULE_CONTENTS_SUCCESS =
  'COMMENT_GET_SCHEDULE_CONTENTS_SUCCESS';

export const SET_SELECTED_EVENT = 'SET_SELECTED_EVENT';
export const GET_SCHEDULED_CONTENTS = 'GET_SCHEDULED_CONTENTS';
export const GET_SCHEDULED_CONTENTS_SUCCESS = 'GET_SCHEDULED_CONTENTS_SUCCESS';

export const UPDATE_EDITING_CONTENT = 'UPDATE_EDITING_CONTENT';
export const RESET_EDITING_CONTENTS = 'RESET_EDITING_CONTENTS';
export const SET_CURRENT_EDITING_CONTENT = 'SET_CURRENT_EDITING_CONTENT';

export const GET_THREADS_INFO = 'GET_THREADS_INFO';
export const GET_THREADS_INFO_SUCCESS = 'GET_THREADS_INFO_SUCCESS';
export const GET_THREADS_INFO_FAILED = 'GET_THREADS_INFO_FAILED';

export const GET_TIKTOK_INFO = 'GET_TIKTOK_INFO';
export const GET_TIKTOK_INFO_SUCCESS = 'GET_TIKTOK_INFO_SUCCESS';
export const GET_TIKTOK_INFO_FAILED = 'GET_TIKTOK_INFO_FAILED';
