export const LOGIN_REQUEST = 'USERS_LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'USERS_LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'USERS_LOGIN_FAILURE';
export const LOGOUT = 'USERS_LOGOUT';
export const LOGOUT_SUCCESS = 'USERS_LOGOUT_SUCCESS';

// save fanpage/content
export const SAVE_LIKED_DATA = 'SAVE_LIKED_DATA';
export const SAVE_LIKED_DATA_SUCCESS = 'SAVE_LIKED_DATA_SUCCESS';
export const SET_LIKED_CONTENTS = 'SET_LIKED_CONTENTS';
export const SET_LIKED_FANPAGES = 'SET_LIKED_FANPAGES';
export const SET_COMPLETE_INFORMATION = 'SET_COMPLETE_INFORMATION'
